[package]
name = "hikmicro-thermal"
version.workspace = true
edition = "2024"

[dependencies]
bytes = { workspace = true }
libc = "0.2"
log = { workspace = true }
md5 = "0.5.0"
normfs = { workspace = true }
prost = { workspace = true }
station_iface = { path = "../../station/shared/station-iface" }
systime = { path = "../../station/shared/systime-rs" }
tokio = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
libusb1-sys = "0.7.0"
norm-uvc-sys = "0.3.0-nc"

[build-dependencies]
prost-build = { workspace = true }

[lib]
path = "src/lib.rs"
