// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AirGradientDevice {
    #[prost(string, tag = "1")]
    pub port_name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub vid: u32,
    #[prost(uint32, tag = "3")]
    pub pid: u32,
    #[prost(string, tag = "4")]
    pub serial_number: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub manufacturer: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub product: ::prost::alloc::string::String,
    #[prost(uint32, tag = "7")]
    pub port_baud_rate: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RxEnvelope {
    #[prost(uint64, tag = "1")]
    pub monotonic_stamp_ns: u64,
    #[prost(uint64, tag = "2")]
    pub local_stamp_ns: u64,
    #[prost(uint64, tag = "3")]
    pub app_start_id: u64,
    #[prost(enumeration = "AirGradientSignalType", tag = "10")]
    pub signal_type: i32,
    #[prost(message, optional, tag = "11")]
    pub device: ::core::option::Option<AirGradientDevice>,
    /// Full raw serial line, e.g. `[W][main:538]: {"pm2_5": 3, ...}`.
    /// Present on CONNECTED and MEASUREMENT signals; empty otherwise.
    #[prost(bytes = "bytes", tag = "20")]
    pub data: ::prost::bytes::Bytes,
    #[prost(string, tag = "50")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AirGradientSignalType {
    AirgradientSignalTypeUnspecified = 0,
    AirgradientConnected = 1,
    AirgradientDisconnected = 2,
    AirgradientMeasurement = 3,
    AirgradientError = 4,
}
impl AirGradientSignalType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            AirGradientSignalType::AirgradientSignalTypeUnspecified => {
                "AIRGRADIENT_SIGNAL_TYPE_UNSPECIFIED"
            }
            AirGradientSignalType::AirgradientConnected => "AIRGRADIENT_CONNECTED",
            AirGradientSignalType::AirgradientDisconnected => "AIRGRADIENT_DISCONNECTED",
            AirGradientSignalType::AirgradientMeasurement => "AIRGRADIENT_MEASUREMENT",
            AirGradientSignalType::AirgradientError => "AIRGRADIENT_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AIRGRADIENT_SIGNAL_TYPE_UNSPECIFIED" => {
                Some(Self::AirgradientSignalTypeUnspecified)
            }
            "AIRGRADIENT_CONNECTED" => Some(Self::AirgradientConnected),
            "AIRGRADIENT_DISCONNECTED" => Some(Self::AirgradientDisconnected),
            "AIRGRADIENT_MEASUREMENT" => Some(Self::AirgradientMeasurement),
            "AIRGRADIENT_ERROR" => Some(Self::AirgradientError),
            _ => None,
        }
    }
}
