// @vitest-environment happy-dom
import { expect, it, vi } from 'vitest';
import { commands, drivers, vesc_trampa } from '@/api/proto.js';

// Generated by station-pi's Go SetBoardCommandSequenceStationCommand helper.
// Covers signed big-endian RPM and the finite sequence's terminal zero.
const goBodies = [
  [-800, '0a0c390040001951353133343238620a0a0508fffffce018fa0162070a050800000000'],
  [800, '0a0c390040001951353133343238620a0a05080000032018fa0162070a050800000000'],
  [-1200, '0a0c390040001951353133343238620a0a0508fffffb5018fa0162070a050800000000'],
  [1200, '0a0c390040001951353133343238620a0a0508000004b018fa0162070a050800000000'],
  [0, '0a0c39004000195135313334323862070a050800000000'],
] as const;

it('encodes RPM commands equivalent to station-pi, including forward, reverse and release', async () => {
  vi.stubGlobal('WebSocket', class { close() {} });
  const { default: manager } = await import('@/api/websocket');
  const packs: Uint8Array[] = [];
  vi.spyOn(manager.normFs, 'enqueuePack').mockImplementation(async (queue, packets) => {
    expect(queue).toBe('commands');
    packs.push(...packets);
    return [];
  });
  const { setVescTrampaRpm } = await import('./commands');
  const uuid = Uint8Array.from(Buffer.from('390040001951353133343238', 'hex'));
  await Promise.all(goBodies.map(([rpm]) => setVescTrampaRpm(uuid, rpm, 250)));
  for (const [index, [, hex]] of goBodies.entries()) {
    const pack = commands.StationCommandsPack.decode(packs[index]);
    expect(pack.commands).toHaveLength(1);
    expect(pack.commands[0].type).toBe(drivers.StationCommandType.STC_VESC_TRAMPA_COMMAND);
    const actual = vesc_trampa.Command.decode(pack.commands[0].body!);
    const expected = vesc_trampa.Command.decode(Uint8Array.from(Buffer.from(hex, 'hex')));
    // Go omits default-valued fields; protobuf.js encodes explicit false/zero.
    const options = { defaults: true, bytes: String, enums: String };
    expect(vesc_trampa.Command.toObject(actual, options)).toEqual(vesc_trampa.Command.toObject(expected, options));
  }
});
