[package]
name = "arduino-pro-4g-gnss"
version.workspace = true
edition = "2024"

[dependencies]
prost = { workspace = true }
bytes = { workspace = true }
log = { workspace = true }
normfs = { workspace = true }
station_iface = { path = "../../station/shared/station-iface" }
systime = { path = "../../station/shared/systime-rs" }
tokio = { workspace = true }
tokio-serial = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }

[lib]
path = "src/lib.rs"
