syntax = "proto3";

package usbvideo;

import "usbvideo/frame.proto";

enum RxEnvelopeType {
    ET_FRAMES = 0;

    ET_DEVICE_CONNECTED       = 1;
    ET_DEVICE_RECORDING_START = 3;
    ET_DEVICE_RECORDING_END   = 4;
    ET_DEVICE_DISCONNECTED    = 5;
    ET_ERROR                  = 6;
    ET_COMMAND                = 7;
    ET_COMMAND_SUCCESS        = 8;
    ET_COMMAND_REJECTED       = 9;
    ET_COMMAND_FAILED         = 10;
}

message RxEnvelope {
    RxEnvelopeType   type  = 1;
    frame.FrameStamp stamp = 2; // for all excluding ET_FRAMES

    Camera                camera  = 5;
    repeated CameraFormat formats = 6;
    string                error   = 7;

    bytes last_inference_queue_ptr = 8;
    
    frame.FramesPack frames = 10;

    TxEnvelope command = 20;
}

enum SetFormatMode {
    SET_FORMAT_MODE_AUTO   = 0;
    SET_FORMAT_MODE_MANUAL = 1;
    SET_FORMAT_MODE_NONE   = 2;
}

message SetFormatCommand {
    SetFormatMode mode = 1;

    // Required for SET_FORMAT_MODE_MANUAL. Ignored for SET_FORMAT_MODE_AUTO
    // and SET_FORMAT_MODE_NONE.
    CameraFormat format = 2;
}

message Command {
    string target_camera_unique_id = 1;

    SetFormatCommand set_format = 10;
}

message TxEnvelope {
    uint64 monotonic_stamp_ns = 1;
    uint64 local_stamp_ns     = 2;
    uint64 app_start_id       = 3;

    bytes  command_id              = 4;
    string target_camera_unique_id = 5;

    Command command = 10;
}

message Camera {
    uint32 vendor_id     = 1;
    uint32 product_id    = 2;
    string serial_number = 3;
    string manufacturer  = 4;
    string product       = 5;
    uint32 bus_number    = 6;
    uint32 device_number = 7;
    string unique_id     = 8;
}

message CameraFormat {
    uint32 fourcc            = 1;
    uint32 index             = 2;
    uint32 width             = 5;
    uint32 height            = 6;
    float  frames_per_second = 7;
    bytes  guid              = 8; // full format id
    uint32 frame_index = 9; // e.g. for libuvc
}
